# -*- coding: utf-8 -*-
"""AI_Resume_Analyzer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1umcKUu-t-C149AV_pTWUBaPU5iZDptfv
"""

from google.colab import files
uploaded = files.upload()

!pip install PyPDF2

from PyPDF2 import PdfReader

pdf_file = list(uploaded.keys())[0]

reader = PdfReader(pdf_file)

text = ""

for page in reader.pages:
    page_text = page.extract_text()

    if page_text:
        text += page_text

print(text)

skills_db = [
    "python",
    "java",
    "sql",
    "html",
    "css",
    "javascript",
    "react",
    "git",
    "machine learning",
    "c",
    "c++"
]

found_skills = []

for skill in skills_db:
    if skill.lower() in text.lower():
        found_skills.append(skill)

print("Skills Found:")
print(found_skills)

score = len(found_skills) * 10

if score > 100:
    score = 100

print("Resume Score:", score, "/100")

suggestions = []

if score < 50:
    suggestions.append("Add more technical skills.")

if "project" not in text.lower():
    suggestions.append("Add project experience.")

if "certificate" not in text.lower():
    suggestions.append("Add certifications.")

print("Suggestions:")

for item in suggestions:
    print("-", item)

print("="*40)
print("AI RESUME ANALYZER REPORT")
print("="*40)

print("\nResume Score:")
print(score, "/100")

print("\nSkills Found:")
for skill in found_skills:
    print("✓", skill)

print("\nSuggestions:")
for item in suggestions:
    print("•", item)